apiVersion: v1
kind: Service
metadata:
  name: uts-devops-service
spec:
  type: NodePort
  selector:
    app: uts-devops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080
